spring.application.name=selfmanager


spring.datasource.url=jdbc:postgresql://localhost:5432/selfmanager
spring.datasource.username=postgres
spring.datasource.password=020420

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

jwt.secret=Th1sIsALearningProjectSecretKeyMakeItLongAndRandom32PlusChars!!
jwt.expiration-ms=86400000