spring.application.name=selfmanager

logging.file.name=logs/selfmanager.log


spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5433/selfmanager}
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:changeme}

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.flyway.enabled=true
spring.flyway.baseline-on-migrate=true

jwt.secret=${JWT_SECRET:Th1sIsALearningProjectSecretKeyMakeItLongAndRandom32PlusChars!!}
jwt.expiration-ms=86400000